= OX Game

This is a simple tic-tac-toe game.

Project requirements:

- JDK 11
- Maven 3.6.2

Project should be build by Maven and run from jar.

To run:

- build project by Maven (`mvn verify` on project directory)
- after the build run `java -jar target/ox-0.5.jar` for default game (3x3)
- to play non-default game you should pass 5 arguments by command line (or 6 when you want to change language).
List of arguments below.

== Command line arguments:

- [0] - name of the first player
- [1] - sign of the first player ("O" or "o" for Naught and "X" or "x" for Cross - second player will get the remaining sign)
- [2] - name of the second player
- [3] - dimension of board (in range from 3 to 30). Board is a square.
- [4] - winning rule - how many field must filled with one type of sign to win (range from 3 to board dimension - 1 (if greater than 3))
- [5] - language tag: "en" for english (default language), "pl" - polish, "ja" - japanese (not completed by now)

Example of command:
`java -jar Aleksander O Czesio 5 3 pl`
Command for playing as Aleksander (naught) and Czesio (cross), board will be 5x5, winning rule 3 and language will be set to polish.

== Python script for automated end-to-end tests

To run this script you need to have Python 3

How to run:
- in project directory run `python3[.version]  automatedTests.py [dimension] [winningRule]`
where dimension and winnin rule are the same things as in ox game (same requirements for them must be provided).
